wip confdb

diff --git a/snap/hooks/observe-view-rosbag2-recorder-parameters b/snap/hooks/observe-view-rosbag2-recorder-parameters
--- a/snap/hooks/observe-view-rosbag2-recorder-parameters
+++ b/snap/hooks/observe-view-rosbag2-recorder-parameters
@@ -1,3 +1,19 @@
-#!/bin/bash -e
+#!/bin/sh -eu
 
-snapctl restart ${SNAP_NAME}.recorder 2>&1 || true
+if snapctl services ${SNAP_NAME}.auto-clean | grep -q inactive; then
+  snapctl start --enable ${SNAP_NAME}.auto-clean 2>&1 || true
+fi
+
+## if auto-clean started correctly we can start recording
+if snapctl services ${SNAP_NAME}.auto-clean | grep -q enabled; then
+  if snapctl services ${SNAP_NAME}.recorder | grep -q inactive; then
+    snapctl start --enable ${SNAP_NAME}.recorder 2>&1 || true
+  fi
+else
+  echo "auto-clean service not enabled - could not start recorder to avoid filling up disk"
+  exit 1
+fi
+
+if snapctl services ${SNAP_NAME}.daily-rotation | grep -q inactive; then
+  snapctl start --enable ${SNAP_NAME}.daily-rotation 2>&1 || true
+fi
